"""initial migration

Revision ID: 147155887822
Revises: None
Create Date: 2016-11-20 20:16:19.302521

"""

# revision identifiers, used by Alembic.
revision = '147155887822'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('handled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'handled')
    ### end Alembic commands ###
